version: "3"

volumes:
  database:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: nodemon
    volumes:
      - ./:/usr/src/app
      - ./docker-config.js:/usr/src/app/config.js
    environment:
      - 'DEBUG=app,app:*'
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080