version: "3"

volumes:
  database:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm run-script dev
    volumes:
      - ./:/usr/src/app
    environment:
      - 'DEBUG=*'
      - 'NODE_ENV=development'
      - 'eWardobe_jwtPrivateKey=3454tgrvstwjwhnbawerq215hyqrg462q53yhgqergqewrgtgdfgbqe3aw534h'
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080