version: "3"

volumes:
  hrgodb:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: nodemon
    volumes:
      # Remaps the container directories for the UTrack Station.
      - ./:/usr/src/app
      - ./docker-config.js:/usr/src/app/config.js
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - hrgodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080