---
openapi: 3.0.0
info:
  version: 1.0.0
  title: E-Wardrobe API
  description: ''
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: "/"
  description: Local Dev
tags:
- name: E-Wardobe
  description: API for E-Wardobe
components:
  securitySchemes:
    jwtAuth:
      type: http
      schema: bearer
      bearerFormat: JWT
consumes:
- application/json
produces:
- application/json
paths:
  "/users":
    get:
      tags:
      - Users
      summary: Get all users
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Users"
    post:
      tags:
      - Users
      security:
      - jwtAuth
      summary: Create a new user in system
      requestBody:
        description: User Object
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/definitions/User"
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/id"
        '400':
          description: Failed. Bad post data.
  "/users/{id}":
    parameters:
    - name: id
      in: path
      required: true
      description: ID of the user that we want to match
      type: string
    get:
      tags:
      - Users
      summary: Get users with given ID
      parameters:
      - in: path
        name: id
        required: true
        description: User with id
        schema:
          "$ref": "#/definitions/id"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/User"
        '404':
          description: Failed. User not found.
    put:
      summary: Update user with given ID
      tags:
      - Users
      requestBody:
        description: User Object
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/definitions/User"
      parameters:
      - in: path
        name: id
        required: true
        description: User with new values of properties
        schema:
          "$ref": "#/definitions/id"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/User"
        '400':
          description: Failed. Bad post data.
        '401':
          description: Unauthorised request.
        '404':
          description: Failed. User not found.
definitions:
  id:
    properties:
      uuid:
        type: string
  User:
    type: object
    properties:
      id:
        type: string
        format: uuid
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
      password:
        type: string
        writeOnly: true
      email:
        type: string
        unique: string
      createdDate:
        type: string
        readOnly: true
      lastUpdated:
        type: string
        readOnly: true
  Users:
    type: object
    properties:
      users:
        type: object
        additionalProperties:
          "$ref": "#/definitions/User"

